version: "3"
services:
  db:
    image: mariadb
    container_name: fena-task-mysql
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    restart: always
    ports:
      - "33066:33066"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=fena-task
      - MYSQL_USER=fena
      - MYSQL_PASSWORD=1234
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  nest_app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - KAFKA_CLIENT_ID=my-app
      - KAFKA_BROKER=kafka:29092
    depends_on:
      - db
      # - kafka
  web:
    build: ./frontend/fena-frontend
    volumes:
      - ./frontend/fena-frontend:/app
      - /app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - nest_app